spring:
  application:
    name: proto1
  datasource:
    url: jdbc:postgresql://localhost:5432/proto1db
    username: postgres
    password: Hellotome@99
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always